version: "3.9"
services:

  db:
    image: saintabel/cl_lab5_event_reminder:db
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DB: "mysql"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"

  bot:
    image: saintabel/cl_lab5_event_reminder:bot
    container_name: bot
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: r2dbc:mysql://db:3306/event_reminder
      SPRING_DATASOURCE_USERNAME: "finley"
      SPRING_DATASOURCE_PASSWORD: "password"