version: "3.9"
services:

db:
  build:
    context: database
    dockerfile: Dockerfile
  image: HolyAbel/event_reminder:db

bot:
  build:
    context: bot
    dockerfile: Dockerfile
  image: HolyAbel/event_reminder:bot
